### ISSUE TITLE
Problem with @keyframes

### ISSUE THREAD

**Issue by lucasmotta** [RadValentin/postcss-prefix-selector#2]
Source:

``` css
body {
  background: red;
}
@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
```

Result:

``` css
.my-prefix {
  background: red;
}
@keyframes fade-out {
  .my-prefix 0% {
    opacity: 1;
  }
  .my-prefix 100% {
    opacity: 0;
  }
}
```

For some reason this utility is also prefixing the "selectors" inside the @keyframes. Is there a way to ignore when inside this block (@keyframes)?
