### ISSUE TITLE
Error with pseudo-class :root

### ISSUE THREAD

**Issue by bpiwowar** [RadValentin/postcss-prefix-selector#98]
The pseudo-class `:root` is not well handled (a prefix is added)

## Input

```js 
prefixer({ prefix: '#app' }
```
and 
```css
:root {
  --bs-blue:#0d6efd;
}
:root .a {
  --bs-blue: #0d6ffd;
}
```

## Current result

```css
#app :root {
  --bs-blue:#0d6efd;
}
#app :root .a {
  --bs-blue: #0d6ffd;
}
```
## Expected

```css
 #app {
  --bs-blue:#0d6efd;
}
#app .a {
  --bs-blue: #0d6ffd;
}
```

## Current work around
```js
  prefixer({
      prefix: '#app',
      transform: (prefix, selector, prefixedSelector) => {
          const found = selector.match(/^\s*:root(\s+\S.*)?$/)
          if (found) {
              return found[1] === undefined ? prefix : `${prefix}${found[1]}`
          }
          return prefixedSelector
      }
  })

```
